name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build linux --tag rust-skia:linux
    - name: Log into GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Tag the image 
      run: docker tag rust-skia:linux ghcr.io/${{ github.repository_owner }}/rust-skia-linux:latest
    - name: Publish the Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/rust-skia-linux:latest
